### ISSUE TITLE
Cannot use tsyringe with electron-react-typescript

### ISSUE THREAD

**Issue by searene** [microsoft/tsyringe#111]
**Describe the bug**
Cannot use tsyringe with [electron-react-typescript](https://github.com/Robinfr/electron-react-typescript)

**To Reproduce**

```bash
git clone --depth=1 git@github.com:Robinfr/electron-react-typescript.git
cd electron-react-typescript
yarn install
yarn add tsyringe reflect-metadata @babel/plugin-proposal-decorators
```

Then open `tsconfig.json` in the project, enable the following two options:

```json
"experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
"emitDecoratorMetadata": true         /* Enables experimental support for emitting type metadata f
```

Then go to `webpack.main.config.js` and change this line

```
["@babel/plugin-proposal-decorators", { "legacy": true }],
```

to

```
["@babel/plugin-proposal-decorators", { "legacy": true }],
['@babel/plugin-proposal-class-properties', { loose: true }],
```

Finally, add two files:

src/main/Client.ts

```typescript
import {inject, singleton} from "tsyringe";
import {Service} from "./Service";

@singleton()
export class Client {

  constructor(@inject(Service) private service: Service) {

  }
}
```

src/main/Service.ts

```typescript
import {injectable} from "tsyringe";

@injectable()
export class Service {

}
```

Add the following lines to `main.ts`

```typescript
import "reflect-metadata";
import { container } from 'tsyringe';
import { Client } from './Client';

...

const client = container.resolve(Client);
console.log(client);
```

Run the project with the command `yarn run start-main-dev --dev`

**Expected behavior**
`client` should be printed and no error was thrown.

**Actual behavior**
An error was thrown.

```
App threw an error during load                                                                                                          
Error: TypeInfo not known for "Client"                                                                                                  
    at InternalDependencyContainer../node_modules/tsyringe/dist/esm5/dependency-container.js.InternalDependencyContainer.construct (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:7620:19)
    at InternalDependencyContainer../node_modules/tsyringe/dist/esm5/dependency-container.js.InternalDependencyContainer.resolveRegistration (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:7500:51)
    at InternalDependencyContainer../node_modules/tsyringe/dist/esm5/dependency-container.js.InternalDependencyContainer.resolve (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:7472:25)
    at Module../src/main/main.ts (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:8330:67)
    at __webpack_require__ (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:20:30)
    at /home/searene/WebstormProjects/electron-react-typescript/dist/main.js:84:18
    at Object.<anonymous> (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:87:10)
    at Object.<anonymous> (/home/searene/WebstormProjects/electron-react-typescript/dist/main.js:8436:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
```

**Version**:
```
"reflect-metadata": "^0.1.13",
"tsyringe": "^4.3.0"
```

**Comment by MeltingMosaic** [comment]
This definitely has something odd going on. I suspect Babel. I'll see about fixing this. Hopefully I can fix the React Native issues at the same time.

**Comment by MeltingMosaic** [comment]
Ok, so the issue here was that Babel was not configured to emit metadata. I fixed this by doing:
```
yarn add --dev babel-plugin-transform-typescript-metadata
```
Then changed my Babel plugin config to:
```
                    plugins: [
                        'babel-plugin-transform-typescript-metadata',
                        ['@babel/plugin-proposal-decorators', { legacy: true }],
                        ['@babel/plugin-proposal-class-properties', { loose: true }]
                    ]
```
