### ISSUE TITLE
Why injectWithTransform method not working, if another class using inject method ?

### ISSUE THREAD

**Issue by restuwahyu13** [microsoft/tsyringe#201]
Why is the **injectWithTransform** method not working, if another class using **inject** method, and I change my code like this, then it is working fine, what is the problem anyone can help me ?, please check my code below if i wrongs implementation.

```ts
constructor(@Inject(RepositoryFlags) private model: RepositoryFlags) {} // works
constructor(@InjectWithTransform(RepositoryFlags, RepositoryFlagsTransformer) private model: Repository<Users>) {} // not works
```

# ENTRYPOINT

```ts
import 'reflect-metadata'
import 'dotenv/config'
import { injectable as Injectable, inject as Inject, container as Container } from 'tsyringe'
import express, { Express } from 'express'
import { createConnection, useContainer } from 'typeorm'
import { Container as TypeContainer } from 'typeorm-typedi-extensions'

import { LoginRoute } from './route'

@Injectable()
class App {
	app: Express

	constructor(@Inject(LoginRoute) private loginRoute: LoginRoute) {
		this.app = express()
	}

	async run(): Promise<void> {
		useContainer(TypeContainer)
		createConnection()
			.then(() => console.log('database connected'))
			.catch(() => console.log('database not connected'))

		this.app.use(this.loginRoute.main())
		this.app.listen(3000, () => console.log('server is running'))
	}
}

// bootstrap express application
Container.resolve<App>(App).run()
```

# Route

```ts
import { injectable as Injectable, inject as Inject } from 'tsyringe'
import { Router } from 'express'

import { LoginController } from './controller'

@Injectable()
export class LoginRoute {
	router: Router

	constructor(@Inject(LoginController) private controller: LoginController) {
		this.router = Router({ strict: true, caseSensitive: true })
	}

	main(): Router {
		this.router.get('/', (req, res) => this.controller.getName(req, res))

		return this.router
	}
}
```

# Controller
```ts
import { injectable as Injectable, inject as Inject } from 'tsyringe'
import { Request, Response } from 'express'
import { OutgoingMessage } from 'http'

import { LoginService } from './service'

@Injectable()
export class LoginController {
	constructor(@Inject(LoginService) private service: LoginService) {}

	getName(req: Request, res: Response): OutgoingMessage {
		return res.status(200).json({ code: res.statusCode, method: req.method, stat_msg: this.service.getName() })
	}
}
```

# Service

```ts
import { injectable as Injectable, injectWithTransform as InjectWithTransform } from 'tsyringe'
import { Repository } from 'typeorm'

import { RepositoryFlags, RepositoryFlagsTransformer } from './di/users'
import { Users } from './models/login'

@Injectable()
export class LoginService {
	constructor(@InjectWithTransform(RepositoryFlags, RepositoryFlagsTransformer) private model: Repository<Users>) {}

	getName(): string {
		console.log(this.model)
		return 'testing'
	}
}
```

# Typeorm DI
```ts
import { Service, Container } from 'typedi'
import { Repository } from 'typeorm'
import { InjectRepository } from 'typeorm-typedi-extensions'
import { Transform } from 'tsyringe/dist/typings/types'

import { Users } from '../models/users'

@Service()
class DependencyInjection {
	constructor(@InjectRepository(Users) public usersRepository: Repository<Users>) {}
}

export class RepositoryFlags {
	public getRepository(): Repository<Users> {
		return Container.get(DependencyInjection).usersRepository
	}
}

export class RepositoryFlagsTransformer implements Transform<RepositoryFlags, Repository<Users>> {
	public transform(flags: RepositoryFlags): Repository<Users> {
		return flags.getRepository()
	}
}
```

# Error Response
```sh
/home/antimalware/Desktop/dummy-project/typedi/node_modules/tsyringe/dist/cjs/dependency-container.js:297
        })();
          ^
Error: Cannot inject the dependency "loginRoute" at position #0 of "App" constructor. Reason:
    Cannot inject the dependency "controller" at position #0 of "LoginRoute" constructor. Reason:
        Cannot inject the dependency "service" at position #0 of "LoginController" constructor. Reason:
            Cannot inject the dependency "model" at position #0 of "LoginService" constructor. Reason:
                Cannot get Connection with name "default" from the ConnectionManager. Make sure you have created the connection and called "useContainer(Container)" in your application before establishing a connection and importing any entity into TypeORM.
    at /home/antimalware/Desktop/dummy-project/typedi/node_modules/tsyringe/dist/cjs/dependency-container.js:324:23
    at Array.map (<anonymous>)
    at /home/antimalware/Desktop/dummy-project/typedi/node_modules/tsyringe/dist/cjs/dependency-container.js:295:38
    at InternalDependencyContainer.construct (/home/antimalware/Desktop/dummy-project/typedi/node_modules/tsyringe/dist/cjs/dependency-container.js:297:11)
    at InternalDependencyContainer.resolve (/home/antimalware/Desktop/dummy-project/typedi/node_modules/tsyringe/dist/cjs/dependency-container.js:114:33)
    at Object.<anonymous> (/home/antimalware/Desktop/dummy-project/typedi/src/app.ts:30:11)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/antimalware/Desktop/dummy-project/typedi/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/antimalware/Desktop/dummy-project/typedi/node_modules/ts-node/src/index.ts:1600:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by restuwahyu13** [comment]
Oke this problem is solved , i add delay in injection like this

```ts
constructor(@Inject(Delay(() => LoginRoute)) private loginRoute: LoginRoute) {
		this.app = express()
}
``
